apiVersion: apps/v1
kind: Deployment
metadata:
  name: babyd-capstone
  namespace: default
spec:
  selector:
    matchLabels:
      run: capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: 3
  template:
    metadata:
      labels:
        run: capstone
    spec:
      containers:
      - name: capstone
        image: babyd/capstone
        ports:
        - containerPort: 80

---        
apiVersion: v1
kind: Service
metadata:
  name: babyd-capstone
  labels:
    run: capstone
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: capstone